services:
  idm:
    container_name: idm
    image: quay.io/keycloak/keycloak:26.1.4
    entrypoint: [ "opt/keycloak/bin/kc.sh", "start-dev", "--import-realm" ]
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - .:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=passKeycloakAdmin
  db-person:
    container_name: db-person
    image: postgres:17.4-bookworm
    ports:
      - 0.0.0.0:5434:5432
    environment:
      - POSTGRES_USER=person
      - POSTGRES_PASSWORD=passGeheim
      - POSTGRES_DB=person
  db-auftrag:
    container_name: db-auftrag
    image: postgres:17.4-bookworm
    ports:
      - 0.0.0.0:5433:5432
    environment:
      - POSTGRES_USER=auftrag
      - POSTGRES_PASSWORD=passGeheim
      - POSTGRES_DB=auftrag
